RANDOM

#rand(); used to generate number between 0 and 1 and all +ve numbers. [0,1)

In [5]:
import numpy as np

variable=np.random.rand(4)      #the parameter says how many random values in the array.
print(variable)
print(f"dimension is {variable.ndim}")
print(type(variable))


#note: everytime you run this cell, you will see the differnt values in the n-d array

[0.21073801 0.84310442 0.45358355 0.37926406]
dimension is 1
<class 'numpy.ndarray'>


#explicitely pass array order i*j

In [7]:
var=np.random.rand(3,4)   #3 rows and 4 column.
print(var)

[[0.85596838 0.97325754 0.92291681 0.41601932]
 [0.61060348 0.25584543 0.22573762 0.29761324]
 [0.709613   0.28178272 0.33149356 0.06240374]]


#randn(); this will generate value close to 0 that may include +ve and -ve as well


In [9]:
var=np.random.randn(5)
print(var)

[ 1.21306181  0.38251436  1.10388031  0.19114589 -0.41552866]


In [10]:
var=np.random.randn(2,3)
print(var)

[[ 0.87983321  1.55493945  0.25678898]
 [-0.68398525 -2.00696055 -0.16255723]]


#ranf(). similar to rand(). [0,1) range.

In [12]:
var=np.random.ranf(4)
print(var)
print(var.ndim)
print(type(var))

[0.91950302 0.99875489 0.6002772  0.54614228]
1
<class 'numpy.ndarray'>


#RANDINT(). it generates random value in the given range by user.


In [16]:
#np.random.randint(min_value,max_value, total_values

var=np.random.randint(5,20,5)

print(var)

[19  6 12 13  6]
