#DATA TYPES

In [2]:
import numpy as np

var=np.array([1,2,3,4])
print("Data types:", var.dtype)

Data types: int64


In [3]:
var=np.array([1.34, 3.45, 8.90])
print("data type: ", var.dtype)

data type:  float64


In [4]:
var=np.array(["a","b","c"])
print("data type:", var.dtype)

data type: <U1


In [5]:
var=np.array([1,"b","c",2])
print("data type:", var.dtype)


data type: <U21


In [7]:
var=np.array([1,2,3.5,6.23])
print("data type:", var.dtype)

#note: here the data is int and float. np array cannot keep different data in one array,
#....so it upcasts everything to the most general that can hold all values. here float is more general.

data type: float64


#FIRST CELL EXAMPLE IS INT64. IT CAN BE CHANGED TO INT8. LET'S SEE HOW??

In [9]:
import numpy as np

var=np.array([1,2,3,4],dtype=np.int8)
print("Data types:", var.dtype)

Data types: int8


#INT INTO FLOAT USING SYMBOL OF FLOAR i.e "f"

In [12]:
import numpy as np

var=np.array([1,2,3,4],dtype="f")
print("Data types:", var.dtype)

Data types: float32


#changing int into float and again into int

In [14]:
import numpy as np

var=np.array([1,2,3,4])
var1=np.float32(var)
var2=np.int_(var1)


print("Data types:", var.dtype)
print("Data types:", var1.dtype)
print("Data types:", var2.dtype)


print(var)
print(var1)
print(var2)

Data types: int64
Data types: float32
Data types: int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


#automatically convert data type using .astype()

In [17]:
var=np.array([1,2,3,4])
var1=var.astype(float)
print(var1.dtype)


float64
