                                       #ARITHMETIC OPERATIONS

#ADD

In [2]:
import numpy as np

var=np.array([1,2,3,4,5])
var+=10
print(var)

[11 12 13 14 15]


In [3]:
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])
varAdd=var1+var2
print(varAdd)

[ 2  4  6  8 10]


#subtract

In [9]:
var=np.array([1,2,3,4,5])
varSub=var-10
print(varSub)

[-9 -8 -7 -6 -5]


In [10]:
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])
varSub=var1-var2
print(varSub)

[0 0 0 0 0]


#divide

In [11]:
var=np.array([1,2,3,4,5])
div=var/10
print(div)

[0.1 0.2 0.3 0.4 0.5]


In [12]:
var1=np.array([10,20,30,40,50])
var2=np.array([5,4,3,2,1])
varDiv=var1/var2
print(varDiv)

[ 2.  5. 10. 20. 50.]


#multiply

In [13]:
var=np.array([1,2,3,4,5])
mul=var*10
print(mul)

[10 20 30 40 50]


In [14]:
var1=np.array([10,20,30,40,50])
var2=np.array([5,4,3,2,1])
varMul=var1*var2
print(varMul)

[50 80 90 80 50]


#modulus

In [16]:
var=np.array([11,20,33,40,55])
modulus=var%10
print(modulus)

[1 0 3 0 5]


In [19]:
var1=np.array([10,20,30,40,50])
var2=np.array([3,4,2,15,1])
varMod=var1%var2
print(varMod)

[ 1  0  0 10  0]
