                                       #ARITHMETIC OPERATIONS with np function

#ADD --- np.add(parameter1, parameter2)

In [1]:
import numpy as np

var=np.array([1,2,3,4,5])
add=np.add(var,3)
print(add)

[4 5 6 7 8]


In [2]:
var1=np.array([1,2,3,4,5])
var2=np.array([1,2,3,4,5])
varAdd=np.add(var1,var2)
print(varAdd)

[ 2  4  6  8 10]


#SUBTRACT---- np.subtract(var1,var2)

In [4]:
var=np.array([1,2,3,4,5])
varSub=np.subtract(var,3)
print(varSub)

[-2 -1  0  1  2]


In [6]:
var1=np.array([1,2,3,4,5])
var2=np.array([2,3,4,5,6])
varSub=np.subtract(var1,var2)
print(varSub)

[-1 -1 -1 -1 -1]


#DIVIDE

In [8]:
var=np.array([3,6,9,12])
div=np.divide(var,3)
print(div)

[1. 2. 3. 4.]


In [11]:
var1=np.array([10,20,30,40,50])
var2=np.array([5,4,3,2,4])
varDiv=np.divide(var1,var2)
print(varDiv)

[ 2.   5.  10.  20.  12.5]


#multiply--- np.multiply(x,x)


In [12]:
var1=np.array([10,20,30,40,50])
var2=np.array([5,4,3,2,4])
varMul=np.multiply(var1,var2)
print(varMul)

[ 50  80  90  80 200]


#MODULUS --np.mod(x,x)

In [14]:
var1=np.array([10,20,30,40,50])
var2=np.array([5,3,9,2,4])
varMod=np.mod(var1,var2)
print(varMod)

[0 2 3 0 2]


In [15]:
import numpy as np

var=np.array([1,2,3,4,5])
mod=np.mod(var,3)
print(mod)

[1 2 0 1 2]


#power----np.power(var,power)

In [16]:
import numpy as np

var=np.array([1,2,3,4,5])
pow=np.pow(var,3)
print(pow)

[  1   8  27  64 125]


In [18]:
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,2])
varPow=np.power(var1,var2)
print(varPow)

[ 1  4 27 16]


#RECIPROCAL ----np.reciprocal(var1)

In [24]:
import numpy as np

var=np.array([1,20,0.5,1/2,5],dtype="f")
reciprocal=np.reciprocal(var)
print(reciprocal)

[1.   0.05 2.   2.   0.2 ]


In [28]:
var=np.array([1,2,3,4,5])
reciprocal=np.reciprocal(var)
print(reciprocal)

#this array is int so result is only given in integer form

[1 0 0 0 0]
