#Arithmetic operations in 2D Array

#2d array multiplication using np function and without using functions

In [9]:
import numpy as np

var=np.array([[1,2,3],[4,5,6]])
result=var*2
print(result)


[[ 2  4  6]
 [ 8 10 12]]


In [13]:
import numpy as np

var=np.array([[1,2,3],[4,5,6]])
result=np.multiply(var,2)
print(result)


[[ 2  4  6]
 [ 8 10 12]]


In [11]:
var1=np.array([[1,2,3],[4,5,6]])
var2=np.array([[1,2,3],[4,5,6]])
result=np.multiply(var1,var2)
print(result)

[[ 1  4  9]
 [16 25 36]]


#adding 2d np array with and without np functions

In [15]:
var=np.array([[1,2,3],[4,5,6]])
result=var+5 #without using np function
print(result)

[[ 6  7  8]
 [ 9 10 11]]


In [16]:
var=np.array([[1,2,3],[4,5,6]])
result=np.add(var,5) #with using np function
print(result)

[[ 6  7  8]
 [ 9 10 11]]
