In [4]:
#array
import numpy as np
x=[1,2,3,4]
a=np.array(x)
print(a)
a #gives type and data stored
print(type(a))



[1 2 3 4]


array([1, 2, 3, 4])

In [7]:
#appending

l=[]
for i in range(5):
    data=int(input("enter:"))
    l.append(data)

print(np.array(l))

enter: 100
enter: 23
enter: 56
enter: 34
enter: 36


[100  23  56  34  36]


In [4]:
#checking the dimension of the array
#use ndim to check
import numpy as np

l=[]
for i in range(5):
    data=int(input("enter:"))
    l.append(data)

print(np.array(l))
x=np.array(l)
print(x.ndim)

enter: 7
enter: 5
enter: 7
enter: 4
enter: 7


[7 5 7 4 7]
1
