In [11]:
# [ ]----1 d
# [[ ]]----2d
#[[[  ]]]---3d array (bracket denotes the dimension)

import numpy as np
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(f"dimension is {array_2d.ndim}")
print(array_2d)


#3-d array

ar_3d=np.array([[[1,2,3],[4,5,6]]])
print(f"the dimension of ar_3d is {ar_3d.ndim}")

print("\n")



dimension is 2
[[1 2 3 4]
 [5 6 7 8]]
the dimension of ar_3d is 3


[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
