In [8]:
#zero; every element filled with zeros in the array

import numpy as np
arr_zero=np.zeros(4) ; # .zero function. pass  the no of zeros inside bracket you want.
                       #one dimensional array
print(arr_zero)
print(type(arr_zero))   #the type of the array is neither list nor tuple but it is ndarray.

[0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr_zero=np.zeros((2,3))   # 2 rows and 3 columns array
print(arr_zero)
print(arr_zero.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
2
