In [10]:
#.ones function. fill array with 1.
# same as .zeros


import numpy as np

arr_one=np.ones(4)
print(arr_one)
print(arr_one.ndim)


[1. 1. 1. 1.]
1


In [13]:
#array filled with 1 with explicitely passing number of rows and columns
import numpy as np


array_one=np.ones((3,4)) #3 rows and 4 columns
print(array_one)

print(f"the dimension is {array_one.ndim}")  #check the dimension of the array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
the dimension is 2
