In [3]:
# .empty function


import numpy as np

arr_empty=np.empty(4)
print(arr_empty)         #we get random value or the value that is already in that memory.

print(type(arr_empty))
print(arr_empty.ndim)

[2.16851034e+243 4.27242994e+180 3.65588327e+233 1.97498397e+166]
<class 'numpy.ndarray'>
1


In [9]:
#explicitely passing rows and columns

array_empty=np.empty((3,4))   # 3 rows and 4 columns with random values

print(array_empty)
print(f"the dimension of the empty array is {array_empty.ndim}")

[[6.95214513e-310 5.13241968e-305 0.00000000e+000 1.26166557e-311]
 [1.21190256e-305 0.00000000e+000 1.26166483e-311 2.00485144e-307]
 [0.00000000e+000 1.26166484e-311 7.56745120e-307 0.00000000e+000]]
the dimension of the empty array is 2


In [12]:
array=np.ones(3,4)
print(array)
print(array.ndim)

TypeError: Cannot interpret '4' as a data type