#DIAGONAL.
IF YOU WANT 1 in diagonal use .eye 

In [6]:
import numpy as np

arr_diagonal=np.eye(3)
print(arr_diagonal)

print(f"the dimesnion is {arr_diagonal.ndim}")

#here you will get 3x3 matrix with diagonal elements 1. it automatically creates a 2D Array.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
the dimesnion is 2


#EXPLICITELY PASSING THE ORDER 

In [10]:
arr_diagonal=np.eye(4,4)
print(arr_diagonal)
print(arr_diagonal.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


#LETS SEE WHAT HAPPENS WHEN UNEQUAL SIZE ARRAY IS PASSED

In [ ]:
arr_